language: python
python:
  - '3.6'
sudo: false

addons:
  postgresql: '9.6'

env:
  matrix:
  - TOXENV=codestyle
  - TOXENV=docs
  - TOXENV=randomorder
  - TOXENV=main

services:
  - redis-server

cache:
  apt: true
  pip: true

before_install:
  - psql --version

install:
  - pip install tox
  - make develop

before_script:
  - psql -c 'create database mailme;' -U postgres

script:
  - RUNNING_IN_CI=True tox -v
