language: python
python:
  - '3.6'
sudo: false

addons:
  postgresql: '9.6'

services:
  - redis-server

cache:
  apt: true
  directories:
    - $HOME/.cache/pip/

before_install:
  - psql --version

install:
  - make develop

before_script:
  - psql -c 'create database mailme;' -U postgres

script:
  - make test
  - make lint
