version: "2"

services:
  web:
    build: .
    command: supervisord -n -c /code/docker/supervisor.conf
    entrypoint: ./scripts/start-docker.sh
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - DATABASE_URL=mysql://root:@postgresql/mailme
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - TERM=xterm-256color
    extra_hosts:
     - "mailme.dev:127.0.0.1"

  redis:
    image: redis:2.8

  db:
    image: postgres/10.1-alpine

  # selenium-firefox:
  #   image: selenium/standalone-firefox-debug
  #   expose:
  #     - "4444"
  #   ports:
  #     - "5900"
  #   shm_size: 2g
  #   links:
  #    - "web:mailme.dev"
