# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 12:26
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256, unique=True, verbose_name='Username')),
                ('name', models.TextField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('uri', models.CharField(blank=True, default=None, help_text='Example: imap+ssl://myusername:mypassword@someserver', max_length=256, null=True, verbose_name='URI')),
                ('from_email', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='From email')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], verbose_name='Sent from')),
                ('to_address', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], verbose_name='Sent to')),
                ('cc_address', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], verbose_name='CC')),
                ('bcc_address', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], verbose_name='BCC')),
                ('reply_to', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Reply-To')),
                ('in_reply_to', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='In reply to')),
                ('headers', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, verbose_name='Headers')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('original', models.TextField(verbose_name='Original (raw) text')),
                ('plain_body', models.TextField(blank=True, verbose_name='Text')),
                ('html_body', models.TextField(blank=True, verbose_name='HTML')),
                ('date', models.DateTimeField(blank=True, verbose_name='Date')),
                ('message_id', models.CharField(max_length=998)),
                ('references', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='References')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='mailme.Mailbox')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailme.Thread'),
        ),
    ]
