# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailme', '0002_auto_20160402_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='provider',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Provider'),
        ),
    ]
