# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailme', '0003_mailbox_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailme.MailboxFolder'),
            preserve_default=False,
        ),
    ]
