# Generated by Django 2.0 on 2018-02-21 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailme', '0005_auto_20160724_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='mailbox',
        ),
        migrations.RemoveField(
            model_name='message',
            name='references',
        ),
        migrations.RemoveField(
            model_name='message',
            name='thread',
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mailboxfolder',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folders', to='mailme.Mailbox'),
        ),
        migrations.AlterField(
            model_name='message',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='mailme.MailboxFolder'),
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
